config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :docs
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
# frozen_string_literal: true

class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
# frozen_string_literal: true

class DocsController < ApplicationController
  before_action :find_doc, only: %i[show edit update destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def new
    @doc = current_user.docs.build
  end

  def show; end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      flash[:notice] = 'Document saved successfully'
      redirect_to @doc
    else
      flash[:alert] = 'Document was not saved!'
      render :new
    end
  end

  def edit; end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render :edit
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/docs_helper.rb
# frozen_string_literal: true

module DocsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
    <h1> Edit the document </h1>

    <%= render "form", doc: @doc %>
    <%= link_to "Cancel", doc_path %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div class="clearfix" id="docs">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
        <a href="<%= (url_for [doc]) %>">
          <div class="doc">
            <p class="title">
                <%= doc.title %>
            </p>
            <p class="date">
                <small>about <%= time_ago_in_words(doc.created_at) %> ago</small>
            </p>
            <p class="content">
                <%= truncate(doc.content, length:50) %>
            </p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Create Doc!</h2>
      <p>Start Creating Documents and Organizing your Life!</p>
      <button>
        <%= link_to "Create Doc", new_doc_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
  <h1> Just for fun </h1>
  <p> New doc </p>
  <%= render "form", doc: @doc %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h1 class="title"><%= @doc.title %></h1>
    <p><%= simple_format(@doc.content) %></p>

    <div class="buttons">
      <%= link_to 'Edit it', edit_doc_path(@doc), class:"button" %>
      <%= link_to 'Delete', docs_path(@doc), method: :delete, data: { confirm: "Are you sure you want to delete this doc?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet | Your life's work!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_inner">
        <%= link_to "FileCabinet", root_path, id: "logo" %>
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Create Doc", new_doc_path %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Log in', new_user_session_path %>
          <% end %>
        </nav>
      </div>   
    </header>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
    <div class="banner_content">
        <h1>File Cabinet</h1>
        <p>Your life's work. Organized, always</p>
        <button>
            <%= link_to "Enter", new_user_registration_path %>
        </button>
    </div>
</div>

<div id="callouts">
    <div class="callout_inner">
        <div class="wrapper">
            <div class="callout">
                <h2>Organize</h2>
                <p>Vestibulum ornare et ligula eget viverra. Nunc venenatis elit in ligula aliquet 
                dignissim sit amet egestas mi. Etiam nec malesuada felis. Fusce vel gravida diam. 
                Aliquam erat volutpat. Mauris congue tempus quam id aliquam. Donec non dui magna. 
                Donec ac mi arcu. Vivamus ornare, nisl nec congue malesuada, nunc dolor eleifend erat, 
                ac sodales ex turpis eu dui. Maecenas accumsan, ex at ultricies molestie, nisl nulla 
                porta mi, sed sodales ipsum risus sit amet ligula. Pellentesque arcu nibh, 
                aliquet eu felis nec, feugiat vulputate ipsum. Curabitur mattis leo ut augue auctor, 
                ut tristique nibh aliquet. Donec eu magna quis est viverra maximus tincidunt nec libero. 
                Aenean vestibulum vehicula est eget dignissim. In vel velit et metus ultricies malesuada
                at a ex. Maecenas et lacus mi.</p>
            </div>
        </div>
    </div>
</div>

<div id="bottom_cta">
    <div class="wrapper">
        <h2>Go Ahead!</h2>
        <br>
        <button>
            <%= link_to "Join Now", new_user_registration_path %>
        </button>
    </div>
</div>